# Kylin Theme Configuration

# Menu
menu:
  首页: /
  服务: /services
  关于我们: /about
  博客: /archives

# Social Links
social:
  telegram: https://t.me/+85251400092

# Company Info
company:
  name: 香港麒麟科技有限公司
  english_name: HONG KONG KYLIN TECHNOLOGY LIMITED
  registration: 76259657
  founded: 2024年3月1日

# Services
services:
  - title: 抖音广告开户
    description: 合规快捷的开户支持
    icon: fa-user-plus
  - title: 广告投放与优化
    description: 精准定位，提升ROI
    icon: fa-bullseye
  - title: 广告代运营
    description: 从创意到数据监控，全程托管
    icon: fa-cogs

# Advantages
advantages:
  - 深入了解中国短视频与社交媒体生态
  - 经验丰富的广告优化与运营团队
  - 一站式跨境投放解决方案
  - 服务专注于海外客户，解决本地化难题

# Footer
footer:
  copyright: 2024 香港麒麟科技有限公司 版权所有

# Color scheme
colors:
  primary: "#3498db"
  secondary: "#2c3e50"
  accent: "#e74c3c"
  background: "#f8f9fa"
  text: "#333333"