name: Simple Hexo Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Hexo CLI
      run: npm install -g hexo-cli

    - name: Install Dependencies
      run: |
        npm install --no-package-lock
        
    - name: Check Theme
      run: |
        echo "Checking theme directory..."
        ls -la themes/ || echo "No themes directory"
        if [ ! -d "themes/bluelake" ]; then
          echo "Bluelake theme not found, downloading..."
          git clone https://github.com/chaooo/hexo-theme-BlueLake.git themes/bluelake
        fi
        
    - name: Generate Site
      run: |
        hexo clean
        hexo generate
        
    - name: List Generated Files
      run: |
        echo "Generated files:"
        ls -la public/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
        force_orphan: true